version: 0.0
os: linux
files:
  - source: /index.php
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: ./scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 300
      runas: root